### ISSUE TITLE
Failed to install scheduler v0.1.2-alpha

### ISSUE THREAD

**Issue by DoktorShift** [bitkarrot/scheduler#19] opened 2024-07-27 00:33 UTC
Thanks for the work on here 💪🏽

Sadly i can not install Scheduler extension.

My Error Log:

```
Jul 27 00:29:13 2016- poetry[658194]: 2024-07-27 00:29:13.28 | INFO | x:0 - "GET /api/v1/extension/scheduler/releases HTTP/1.1" 200
Jul 27 00:29:15 2016- poetry[658194]: 2024-07-27 00:29:15.03 | INFO | x:0 - "GET /api/v1/extension/release/bitkarrot/scheduler/v0.1.2-alpha HTTP/1.1" 200
Jul 27 00:29:16 2016- poetry[658194]: 2024-07-27 00:29:16.16 | INFO | Downloading extension scheduler (v0.1.2-alpha).
Jul 27 00:29:16 2016- poetry[658194]: 2024-07-27 00:29:16.35 | INFO | Extracting extension scheduler (v0.1.2-alpha).
Jul 27 00:29:16 2016- poetry[658194]: 2024-07-27 00:29:16.36 | SUCCESS | Extension Scheduler (v0.1.2-alpha) installed.
Jul 27 00:29:16 2016- poetry[658194]: running migration scheduler.3
Jul 27 00:29:16 2016-r poetry[658194]: 2024-07-27 00:29:16.37 | WARNING | (sqlite3.OperationalError) near "DROP": syntax error
Jul 27 00:29:16 2016- poetry[658194]: [SQL: ALTER TABLE scheduler.jobs DROP COLUMN command;]
Jul 27 00:29:16 2016- poetry[658194]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Jul 27 00:29:16 2016- poetry[658194]: 2024-07-27 00:29:16.38 | ERROR | HTTPException 500: Failed to install extension scheduler (v0.1.2-alpha).
Jul 27 00:29:16 2016- poetry[658194]: 2024-07-27 00:29:16.38 | INFO | x.5:0 - "POST /api/v1/extension HTTP/1.1" 500
```

Version:
Lnbits:  v0.12.9
database: sqlite

**Comment by bitkarrot** [comment] 2024-07-27 02:59
@DoktorShift did you already have an old version of scheduler previously installed? 

the current release is v0.12.10 and higher, perhaps we should lock the min version

**Comment by bitkarrot** [comment] 2024-07-27 03:10
Yep - just tried min version 0.12.10 works

<img width="661" alt="Screenshot 2024-07-26 at 8 09 33 PM" src="https://github.com/user-attachments/assets/8c92b0ad-257d-4ca6-ba6f-fc56c1bbb6af">

**Comment by DoktorShift** [comment] 2024-07-27 17:50
Yes i had but i previously removed old database.

I did it again on v0.12.10 

```
Jul 27 17:45:53 2016-espressobar poetry[668303]: 2024-07-27 17:45:53.66 | SUCCESS | Database removed for extension 'scheduler'
Jul 27 17:45:53 2016-espressobar poetry[668303]: 2024-07-27 17:45:53.66 | INFO | x.5:0 - "DELETE /api/v1/extension/scheduler/db HTTP/1.1" 200
Jul 27 17:45:56 2016-espressobar poetry[668303]: 2024-07-27 17:45:56.34 | INFO | x.5:0 - "GET /api/v1/extension/scheduler/releases HTTP/1.1" 200
Jul 27 17:45:58 2016-espressobar poetry[668303]: 2024-07-27 17:45:58.38 | INFO | x.5:0 - "GET /api/v1/extension/release/bitkarrot/scheduler/v0.1.2-alpha-2 HTTP/1.1" 200
Jul 27 17:45:59 2016-espressobar poetry[668303]: 2024-07-27 17:45:59.54 | INFO | Downloading extension scheduler (v0.1.2-alpha-2).
Jul 27 17:45:59 2016-espressobar poetry[668303]: 2024-07-27 17:45:59.87 | INFO | Extracting extension scheduler (v0.1.2-alpha-2).
Jul 27 17:45:59 2016-espressobar poetry[668303]: 2024-07-27 17:45:59.89 | SUCCESS | Extension Scheduler (v0.1.2-alpha-2) installed.
Jul 27 17:45:59 2016-espressobar poetry[668303]: running migration scheduler.1
Jul 27 17:45:59 2016-espressobar poetry[668303]: running migration scheduler.2
Jul 27 17:46:00 2016-espressobar poetry[668303]: running migration scheduler.3
Jul 27 17:46:00 2016-espressobar poetry[668303]: 2024-07-27 17:46:00.05 | WARNING | (sqlite3.OperationalError) near "DROP": syntax error
Jul 27 17:46:00 2016-espressobar poetry[668303]: [SQL: ALTER TABLE scheduler.jobs DROP COLUMN command;]
Jul 27 17:46:00 2016-espressobar poetry[668303]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Jul 27 17:46:00 2016-espressobar poetry[668303]: 2024-07-27 17:46:00.06 | ERROR | HTTPException 500: Failed to install extension scheduler (v0.1.2-alpha-2).
Jul 27 17:46:00 2016-espressobar poetry[668303]: 2024-07-27 17:46:00.06 | INFO | x.5:0 - "POST /api/v1/extension HTTP/1.1" 500
```

**Comment by bitkarrot** [comment] 2024-07-28 01:26
@DoktorShift it appears you have previously installed scheduler extension on this 0.12.10, and are attempting to migrate from it, this is not a fresh install, am I correct?  Or is this an older version such as 0.12.9?

**Comment by bitkarrot** [comment] 2024-07-31 07:03
@DoktorShift  I cannot reproduce your error but it seems that because your tables were previously dropped, it cannot be dropped again, so that is possibly the cause of the error. Closing issue for now.

**Closed as completed by bitkarrot** 2024-07-31 07:03 UTC
